package manifest

const geminiSunsetDeadline = "2026-06-18"

var allClients = []ClientManifest{
	{
		ID:        ClientClaudeDesktop,
		Name:      "Claude Desktop",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerFile,
		DocsURL:   "https://modelcontextprotocol.io/quickstart/user",
		Candidates: []ConfigCandidate{
			{
				Label:        "user-darwin",
				PathTemplate: "{{.Home}}/Library/Application Support/Claude/claude_desktop_config.json",
				Platforms:    []string{"darwin"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
			{
				Label:        "user-linux",
				PathTemplate: "{{.Home}}/.config/Claude/claude_desktop_config.json",
				Platforms:    []string{"linux"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
		},
		Sources: []SourceRef{
			{URL: "https://modelcontextprotocol.io/quickstart/user", Title: "MCP User Quickstart", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientClaudeCode,
		Name:      "Claude Code",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerCLI,
		CLIName:   "claude",
		DocsURL:   "https://docs.anthropic.com/en/docs/claude-code/mcp",
		Candidates: []ConfigCandidate{
			{
				Label:        "project",
				PathTemplate: "{{.Workspace}}/.mcp.json",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeProject,
				Format:       FormatJSON,
				MutationKind: MutationClaudeCodeCLI,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceMedium,
				Precedence:   10,
				GitWarning:   true,
			},
			{
				Label:        "user",
				PathTemplate: "{{.Home}}/.claude.json",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationClaudeCodeCLI,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    false,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
		},
		Sources: []SourceRef{
			{URL: "https://docs.anthropic.com/en/docs/claude-code/mcp", Title: "Claude Code MCP", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientCursor,
		Name:      "Cursor",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerFile,
		DocsURL:   "https://docs.cursor.com/context/model-context-protocol",
		Candidates: []ConfigCandidate{
			{
				Label:        "project",
				PathTemplate: "{{.Workspace}}/.cursor/mcp.json",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeProject,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceMedium,
				Precedence:   10,
				GitWarning:   true,
			},
			{
				Label:        "global",
				PathTemplate: "{{.Home}}/.cursor/mcp.json",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeGlobal,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
		},
		Sources: []SourceRef{
			{URL: "https://docs.cursor.com/context/model-context-protocol", Title: "Cursor MCP", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientVSCode,
		Name:      "VS Code",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerFile,
		DocsURL:   "https://code.visualstudio.com/docs/copilot/chat/mcp-servers",
		Candidates: []ConfigCandidate{
			{
				Label:        "workspace",
				PathTemplate: "{{.Workspace}}/.vscode/mcp.json",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeWorkspace,
				Format:       FormatJSON,
				MutationKind: MutationNamedServer,
				RootKey:      "servers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceMedium,
				Precedence:   10,
				GitWarning:   true,
			},
			{
				Label:        "user-darwin",
				PathTemplate: "{{.Home}}/.vscode/mcp.json",
				Platforms:    []string{"darwin"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationNamedServer,
				RootKey:      "servers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
				GitWarning:   true,
			},
			{
				Label:        "user-linux",
				PathTemplate: "{{.Home}}/.config/Code/User/mcp.json",
				Platforms:    []string{"linux"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationNamedServer,
				RootKey:      "servers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
		},
		Sources: []SourceRef{
			{URL: "https://code.visualstudio.com/docs/copilot/chat/mcp-servers", Title: "VS Code MCP", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientWindsurf,
		Name:      "Windsurf",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerFile,
		DocsURL:   "https://docs.windsurf.com/plugins/cascade/mcp",
		Candidates: []ConfigCandidate{
			{
				Label:        "user-darwin",
				PathTemplate: "{{.Home}}/.codeium/windsurf/mcp_config.json",
				Platforms:    []string{"darwin"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
			{
				Label:        "user-linux",
				PathTemplate: "{{.Home}}/.codeium/mcp_config.json",
				Platforms:    []string{"linux"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
			{
				Label:           "legacy-linux",
				PathTemplate:    "{{.Home}}/.codeium/windsurf/mcp_config.json",
				Platforms:       []string{"linux"},
				Scope:           ScopeLegacy,
				Format:          FormatJSON,
				MutationKind:    MutationMCPServers,
				RootKey:         "mcpServers",
				URLField:        "url",
				Creatable:       true,
				Confidence:      ConfidenceMedium,
				Precedence:      30,
				Deprecated:      true,
				ReplacedBy:      "user-linux",
				DeprecationNote: "legacy Linux Windsurf location preserved for migration detection",
			},
		},
		Sources: []SourceRef{
			{URL: "https://docs.windsurf.com/plugins/cascade/mcp", Title: "Windsurf MCP", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientZed,
		Name:      "Zed",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerFile,
		DocsURL:   "https://zed.dev/docs/assistant/model-context-protocol",
		Candidates: []ConfigCandidate{
			{
				Label:        "user",
				PathTemplate: "{{.Home}}/.config/zed/settings.json",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationNamedServer,
				RootKey:      "context_servers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
		},
		Sources: []SourceRef{
			{URL: "https://zed.dev/docs/assistant/model-context-protocol", Title: "Zed MCP", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientRooCode,
		Name:      "Roo Code",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerFile,
		DocsURL:   "https://docs.roocode.com/features/mcp/using-mcp-in-roo",
		Candidates: []ConfigCandidate{
			{
				Label:        "user-darwin",
				PathTemplate: "{{.Home}}/Library/Application Support/Code/User/globalStorage/saoudrizwan.claude-dev/settings/mcp_settings.json",
				Platforms:    []string{"darwin"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
			{
				Label:        "user-linux",
				PathTemplate: "{{.Home}}/.config/Code/User/globalStorage/saoudrizwan.claude-dev/settings/mcp_settings.json",
				Platforms:    []string{"linux"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
		},
		Sources: []SourceRef{
			{URL: "https://docs.roocode.com/features/mcp/using-mcp-in-roo", Title: "Roo Code MCP", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientOpenCode,
		Name:      "OpenCode",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerFile,
		DocsURL:   "https://opencode.ai/docs/mcp",
		Candidates: []ConfigCandidate{
			{
				Label:        "global-darwin",
				PathTemplate: "{{.Home}}/.opencode.json",
				Platforms:    []string{"darwin"},
				Scope:        ScopeGlobal,
				Format:       FormatJSONC,
				MutationKind: MutationNamedServer,
				RootKey:      "mcp",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
			{
				Label:        "global-linux",
				PathTemplate: "{{.Home}}/.config/opencode/opencode.json",
				Platforms:    []string{"linux"},
				Scope:        ScopeGlobal,
				Format:       FormatJSONC,
				MutationKind: MutationNamedServer,
				RootKey:      "mcp",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
		},
		Sources: []SourceRef{
			{URL: "https://opencode.ai/docs/mcp", Title: "OpenCode MCP", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientKiro,
		Name:      "Kiro",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerFile,
		DocsURL:   "https://kiro.dev/docs/mcp",
		Candidates: []ConfigCandidate{
			{
				Label:        "user",
				PathTemplate: "{{.Home}}/.kiro/settings/mcp.json",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
		},
		Sources: []SourceRef{
			{URL: "https://kiro.dev/docs/mcp", Title: "Kiro MCP", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientGeminiCLI,
		Name:      "Gemini CLI",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerFile,
		CLIName:   "gemini",
		DocsURL:   "https://github.com/google-gemini/gemini-cli",
		Candidates: []ConfigCandidate{
			{
				Label:        "settings",
				PathTemplate: "{{.Home}}/.gemini/settings.json",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
			{
				Label:           "legacy-darwin-mcp",
				PathTemplate:    "{{.Home}}/.gemini/mcp_config.json",
				Platforms:       []string{"darwin"},
				Scope:           ScopeLegacy,
				Format:          FormatJSON,
				MutationKind:    MutationBareMCPServers,
				RootKey:         "",
				URLField:        "url",
				Creatable:       true,
				Confidence:      ConfidenceLow,
				Precedence:      30,
				Deprecated:      true,
				ReplacedBy:      "settings",
				DeprecationNote: "legacy macOS Gemini MCP config path",
			},
		},
		Warnings: []ClientWarning{
			{Code: "sunset", Message: "Gemini CLI is deprecated and should migrate to Antigravity.", Deadline: geminiSunsetDeadline},
		},
		Sources: []SourceRef{
			{URL: "https://github.com/google-gemini/gemini-cli", Title: "Gemini CLI", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientAntigravityCLI,
		Name:      "Antigravity CLI",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerFile,
		CLIName:   "antigravity",
		DocsURL:   "https://antigravity.google/docs/mcp",
		Candidates: []ConfigCandidate{
			{
				Label:        "settings",
				PathTemplate: "{{.Home}}/.gemini/antigravity-cli/settings.json",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
			{
				Label:           "legacy-darwin-mcp",
				PathTemplate:    "{{.Home}}/.gemini/antigravity-cli/mcp_config.json",
				Platforms:       []string{"darwin"},
				Scope:           ScopeLegacy,
				Format:          FormatJSON,
				MutationKind:    MutationBareMCPServers,
				RootKey:         "",
				URLField:        "url",
				Creatable:       true,
				Confidence:      ConfidenceLow,
				Precedence:      30,
				Deprecated:      true,
				ReplacedBy:      "settings",
				DeprecationNote: "legacy macOS Antigravity CLI MCP config path",
			},
		},
		Sources: []SourceRef{
			{URL: "https://antigravity.google/docs/mcp", Title: "Antigravity MCP", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientAntigravity,
		Name:      "Antigravity IDE",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerFile,
		DocsURL:   "https://antigravity.google/docs/mcp",
		Candidates: []ConfigCandidate{
			{
				Label:        "repo-current",
				PathTemplate: "{{.Home}}/.gemini/config/mcp_config.json",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeUser,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
			{
				Label:        "alternate-symlink",
				PathTemplate: "{{.Home}}/.gemini/antigravity/mcp_config.json",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeManaged,
				Format:       FormatJSON,
				MutationKind: MutationMCPServers,
				RootKey:      "mcpServers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceMedium,
				Precedence:   10,
				SymlinkHint:  true,
			},
		},
		Warnings: []ClientWarning{
			{Code: "path-dispute", Message: "Antigravity path metadata includes both the repo-supported path and the newer symlink-based path until migration behavior is verified."},
		},
		Sources: []SourceRef{
			{URL: "https://antigravity.google/docs/mcp", Title: "Antigravity MCP", VerifiedAt: "2026-05-21"},
		},
	},
	{
		ID:        ClientCodexCLI,
		Name:      "Codex CLI",
		Platforms: []string{"darwin", "linux"},
		Manager:   ManagerCLI,
		CLIName:   "codex",
		DocsURL:   "https://developers.openai.com/codex/mcp",
		Candidates: []ConfigCandidate{
			{
				Label:        "project",
				PathTemplate: "{{.Workspace}}/.codex/config.toml",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeProject,
				Format:       FormatTOML,
				MutationKind: MutationCodexTOML,
				RootKey:      "mcp_servers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceMedium,
				Precedence:   10,
			},
			{
				Label:        "user",
				PathTemplate: "{{.Home}}/.codex/config.toml",
				Platforms:    []string{"darwin", "linux"},
				Scope:        ScopeUser,
				Format:       FormatTOML,
				MutationKind: MutationCodexTOML,
				RootKey:      "mcp_servers",
				URLField:     "url",
				Creatable:    true,
				Confidence:   ConfidenceHigh,
				Precedence:   20,
			},
		},
		Sources: []SourceRef{
			{URL: "https://developers.openai.com/codex/mcp", Title: "Codex MCP", VerifiedAt: "2026-05-21"},
		},
	},
}
